Feature/un 9
freeverseio/laos-universal-node pull request #1
Opened 2023-10-06 08:40 UTC by kudlaj

2023-10-06 08:44 UTC, kudlaj commented
This first feature contains the following tasks:

- add a simple go project with a json-rpc server that has one method: System.Up
- create the Dockerfile 
- create a README

2023-10-06 09:40 UTC, zorjak commented on Dockerfile
> +FROM golang:1.20-alpine AS builder
can we use the latest version of go?

2023-10-06 13:26 UTC, zorjak approved these changes

2023-10-06 16:59 UTC, luispdm requested changes

2023-10-06 16:59 UTC, luispdm commented on README.md
> +Right now there is only on method supported:
Typo: one instead of on

2023-10-06 16:59 UTC, luispdm commented on Dockerfile
> +# Use an official Go runtime as a parent image
I have a few suggestions for this:
1. choose a fixed version for both builder and final stages. I suggest: `golang:1.21-alpine3.18` and `alpine:3.18.4`
2. change `RUN mkdir...` to `RUN addgroup -g 1000 nodegroup && adduser -D nodeuser -u 1000 -G nodegroup` as it adds clarity
3. remove `go mod download` and `RUN apk --no-cache add ca-certificates` as they are not required
4. you can swap `RUN CGO_ENABLED=1 go build -race -installsuffix 'static' -o app .` with `RUN go build -race -o app .` as we are not linking any C library to our executable at the moment
5. to install the C compiler, you can replace `RUN apk add --no-cache ca-certificates git alpine-sdk linux-headers` with `RUN apk add --no-cache build-base=~0.5`. The `~0.5` is gonna match 0.5 and any minor update made to the package, source: https://wiki.alpinelinux.org/wiki/Alpine_Package_Keeper#Holding_a_specific_package_back. You can see the latest versions of each alpine package here: https://pkgs.alpinelinux.org/packages
6. there's one extra space you can remove between `COPY --from=builder` and `/app`
7. remove all the comments. I think, at least for now, all the instructions are pretty self-explanatory
8. if some instructions take too much space on the line, please use line breaks `\` and indentation

At the end of the day, I managed to end up with the following:
```Dockerfile
FROM golang:1.21-alpine3.18 AS builder
# Add C compiler to build the executable with race detection enabled
RUN apk add --no-cache build-base=~0.5

RUN addgroup -g 1000 nodegroup && \
    adduser -D nodeuser -u 1000 -G nodegroup

WORKDIR /app
COPY ./go .
RUN go build -race -o app .

FROM alpine:3.18.4 AS final

WORKDIR /app
COPY --from=builder /app /app

CMD ["./app"]
USER nobody:nobody

```

Some of the suggestions came from the following tools (lint and vulnerability scanning):
https://trivy.dev/
https://github.com/hadolint/hadolint
https://docs.docker.com/scout/

Clever use of `USER nobody:nobody` 👏

2023-10-09 07:55 UTC, AlexRipoll requested changes

2023-10-09 07:55 UTC, AlexRipoll commented on go/main.go
> +		w.WriteHeader(200)
I suggest replacing 200 by `http.StatusOK` for greater clarity

2023-10-09 07:55 UTC, AlexRipoll commented on go/main.go
> +			fmt.Println("Error while serving JSON request", err)
Shouldn't the header status code be updated in the event of an error?

2023-10-09 11:27 UTC, AlexRipoll approved these changes

2023-10-10 05:36 UTC, merged