Feature/un 81 Update Unode from Laos breaking changes
freeverseio/laos-universal-node pull request #31
Opened 2023-11-21 11:31 UTC by AlexRipoll

2023-11-21 13:43 UTC, luispdm requested changes

2023-11-21 13:43 UTC, luispdm commented on cmd/main.go
> +			_, lastScannedBlock, err := s.ScanEvents(ctx, big.NewInt(int64(startingBlock)), big.NewInt(int64(lastBlock)), nil) // TODO choose if c.EvoContract should be a []string
Can you change the TODO to: "change contracts from []string to ...string" and move the comment to scan.go please?

2023-11-22 08:18 UTC, kudlaj approved these changes

2023-11-22 09:25 UTC, luispdm approved these changes

2023-11-22 09:32 UTC, merged