Feature/un 19 3 Adding CI & Deployment
freeverseio/laos-universal-node pull request #5
Opened 2023-10-10 05:51 UTC by kudlaj

In this feature we add:

- CI/CD 
- k8 configuration
- configure linter

2023-10-11 11:20 UTC, luispdm requested changes

2023-10-11 11:20 UTC, luispdm commented on go/main.go
> +		ReadTimeout:  5 * time.Second,
Mental note for the future, not for now as this is just the first iteration: we need to set up `ReadHeaderTimeout` too

2023-10-11 11:20 UTC, luispdm commented on .golangci.yml
> +    - ineffassign
I think `revive` and `unparam` add value, we should add them. You can find the full list of supported linters here: https://golangci-lint.run/usage/linters/. `lll` would be nice for long lines but I leave that up to you.
If the linters raise warnings/errors that we can ignore for now, you can add a comment like this next to the offending line: `//nolint:$LINTER` (e.g. `//nolint:unparam`).

2023-10-11 11:20 UTC, luispdm commented on Dockerfile
> +COPY --from=builder /app /app
I forgot to edit this in the UN-9 PR. Please change it to: `COPY --from=builder /app/universalnode .` so we only copy the binary

2023-10-11 11:20 UTC, luispdm commented on Dockerfile
> +USER nobody:nobody
Add a new line at the end of the file please. Thank you

2023-10-11 11:20 UTC, luispdm commented on scripts/install-helmfile.sh
> +helm plugin install https://github.com/databus23/helm-diff --version v3.6.0
Update helm-diff to v3.8.1 and helmfile to v0.157.0 please

2023-10-11 11:20 UTC, luispdm commented on .circleci/config.yml
> +  helm: circleci/helm@2.0.1
Update to 3.0.0

2023-10-11 11:20 UTC, luispdm commented on .circleci/config.yml
> +      - image: cimg/base:2022.12
Update to 2023.09 here and in the rest of the file where cimg/base is used.
If you prefer, you can declare executors once and use them in the rest of the file. Example:
```yml
executors:
  cimg-base:
    docker:
      - image: cimg/base:2023.09
  another:
    docker:
      - image: ubuntu-2004:202201-02
# then use it:
dockerize:
  description: Something
  executor: cimg-base
```

2023-10-11 11:20 UTC, luispdm commented on .circleci/config.yml
> +      - image: ipfs/kubo:v0.18.1
The kubo image is not required for now

2023-10-11 11:20 UTC, luispdm commented on .circleci/config.yml
> +            - deployment_test
Add `dockerize` (or `dockerize_universalnode`, I am not sure which of the two works, please look that up) and a new line at the end of the file, please

2023-10-11 11:20 UTC, luispdm commented on .circleci/config.yml
> +      - image: cimg/deploy:2022.11
Update to 2023.09 please

2023-10-11 11:20 UTC, luispdm commented on .circleci/config.yml
> +          kubectl-version: "v1.16.12"
I would suggest upgrading this to match the version of our cluster

2023-10-11 11:20 UTC, luispdm commented on .circleci/config.yml
> +  deployment_test:
Rename it to: `deployment_lint` pleae

2023-10-11 11:20 UTC, luispdm commented on deployment/charts/universalnode/Chart.yaml
> +appVersion: 1.16.0
Change this to 0.1.0 as well please

2023-10-11 11:20 UTC, luispdm commented on deployment/charts/universalnode/templates/deployment.yaml
> +        args: []
Please remove `args` as it is not used for now

2023-10-11 11:20 UTC, luispdm commented on deployment/charts/universalnode/templates/deployment.yaml
> +          limits:
I suggest changing limits to `2Gi` for `memory` and `2` for `cpu`. It's better to start with low requirements IMHO

2023-10-11 11:20 UTC, luispdm commented on deployment/helmfile.yaml
> +      - debug: true
Please remove `debug` as it is not used for now

2023-10-11 11:20 UTC, luispdm commented on deployment/charts/universalnode/templates/deployment.yaml
> +      app.kubernetes.io/app: universalnode
Please, replace `universalnode` here and on lines 14 and 17 with `{{ .Values.name }}`. Thanks

2023-10-11 11:20 UTC, luispdm commented on deployment/charts/universalnode/templates/service.yaml
> +apiVersion: v1
Mental note: if we want the app to be reachable outside the cluster we have to add an ingress

2023-10-11 15:38 UTC, kudlaj commented on .circleci/config.yml
> +          kubectl-version: "v1.16.12"
how can we check it?

2023-10-11 15:38 UTC, kudlaj commented on .golangci.yml
> +    - ineffassign
I will leave it like it is for now

2023-10-11 15:38 UTC, kudlaj commented on .circleci/config.yml
> +  helm: circleci/helm@2.0.1
I will not change this since it will bring a lot of problems.

2023-10-12 07:05 UTC, luispdm commented on .circleci/config.yml
> +          version: v3.11.0
Ops. I forgot to mention that you can update this to install the latest version, v3.13.0 https://github.com/helm/helm/releases/tag/v3.13.0

2023-10-12 07:14 UTC, luispdm commented on .circleci/config.yml
> +          version: v3.11.0
Resolving conversation as the upgrade has been performed

2023-10-12 07:27 UTC, luispdm commented on .circleci/config.yml
> +  helm: circleci/helm@2.0.1
fixed https://github.com/freeverseio/laos-universal-node/pull/5/commits/def72d51d0e03e347e785132d2e9af4a371a7310, resolving the conversation

2023-10-12 07:30 UTC, luispdm commented on .circleci/config.yml
> +          kubectl-version: "v1.16.12"
I cannot check the version of our cluster as I don't have that level of permission. We should ask the people with superpowers 💪

2023-10-12 07:36 UTC, luispdm commented on deployment/charts/universalnode/templates/deployment.yaml
> +          limits:
You've changed the memory in the requests and the CPU in the limits. I meant to change the values in the `limits` section only, sorry. Please change it to make it look like this:
```yml
requests:
  memory: "512Mi"
  cpu: "500m"
limits:
  memory: "2Gi"
  cpu: "2"
```

2023-10-13 07:47 UTC, luispdm approved these changes

2023-10-13 11:45 UTC, AlexRipoll approved these changes
looks good to me

2023-10-13 11:48 UTC, merged