Feature/un 101 Translate blocktags for proxy calls
freeverseio/laos-universal-node pull request #61
Opened 2023-12-19 09:54 UTC by kudlaj

- If a query is triggered with “latest” block, the “unode” will process it in the latest block it has processed, not the latest block on the ownershipchain.

- If a query is triggered with a block number larger than the latest processes block by the uNode it fails in the same way that a regular node will fail if you ask for a block not processed yet.

2023-12-19 15:44 UTC, zorjak approved these changes

2023-12-19 15:44 UTC, zorjak commented on cmd/server/api/rpcmethods.go
> +//	var rpcMethodsWithCountByHash = map[string]RPCMethod{
should we remove this comment if it is not needed? or at least write a comment on why this is commented (not supported)

2023-12-20 12:27 UTC, AlexRipoll requested changes

2023-12-20 12:27 UTC, AlexRipoll commented on cmd/server/api/rpcmethods.go
> +func (b *ProxyRPCMethodManager) HasRPCMethodWithBlocknumber(methodName string) (RPCMethod, bool) {
Camel case typo in `HasRPCMethodWithBlocknumber`

2023-12-20 17:11 UTC, luispdm requested changes

2023-12-20 17:11 UTC, luispdm commented on cmd/server/api/rpcmiddleware.go
> +type EthCallParamsRPCRequest struct {
If you do not plan to use it in external packages tests, this should be unexported

2023-12-20 17:11 UTC, luispdm commented on cmd/server/api/rpcmethods.go
> +type BlockTag string
Make it unexported, as well as: FilterObject, Block, Transaction and the constants Latest, Pending etc. and CompareHex(), please

2023-12-20 17:11 UTC, luispdm commented on cmd/server/api/rpcproxyhandler.go
> +	// check if we have to replace the block tag
I think this comment refers to linees 16-26 instead of 68-78

2023-12-20 17:11 UTC, luispdm commented on cmd/server/api/rpcmethods.go
> +func replaceBlockTagWithHash(req *JSONRPCRequest, position int, blockNumberHash string) error {
Rename "blockNumberHash" to "blockNumberUnode" here, as well as in "replaceBlockTagFromObject" and "getBlockNumber", please.

I also think that this function should be called: "replaceBlockTagWithBlockNumber".

2023-12-21 08:42 UTC, AlexRipoll approved these changes

2023-12-21 09:39 UTC, luispdm approved these changes

2023-12-21 09:44 UTC, merged