scan only ownership contracts pointing to the targeted evochain
freeverseio/laos-universal-node pull request #66
Opened 2023-12-27 14:55 UTC by luispdm

2023-12-27 23:32 UTC, zorjak requested changes

2023-12-27 23:32 UTC, zorjak commented on internal/config/config.go
> +	case strings.Contains(strings.ToLower(c.EvoRpc), "klaos"):
Maybe I am wrong but I think this is a bug. evoRpc is a domain name. 
It can be that evoRpc provider runs `caladan` node but gives it domain name that contains `klaos`?

Maybe we should call some node API to decide is it `caladan` or `klaos`? maybe by calling ChainId?

2023-12-28 09:15 UTC, luispdm commented on internal/config/config.go
> +	case strings.Contains(strings.ToLower(c.EvoRpc), "klaos"):
Agreed. Changes pushed

2023-12-28 09:17 UTC, zorjak approved these changes

2023-12-28 09:17 UTC, merged