Feature/un 107
freeverseio/laos-universal-node pull request #75
Opened 2024-01-08 10:02 UTC by AlexRipoll

- Filtering events by topics
- Removing Approval, ApproveForAll and NewCollection events from scanner

2024-01-08 14:30 UTC, luispdm requested changes

2024-01-08 14:30 UTC, luispdm commented on internal/platform/scan/scan.go
>  	// TODO optionally filter by topics?
Remove this TODO

2024-01-08 14:30 UTC, luispdm commented on internal/platform/scan/scan.go
> -	collectionAbi, err := abi.JSON(strings.NewReader(contract.CollectionMetaData.ABI))
Since this is not used anymore, I suggest deletiung `internal/platform/blockchain/contract/evolutioncollectionfactory.go`

2024-01-08 15:08 UTC, luispdm approved these changes

2024-01-09 09:44 UTC, kudlaj approved these changes

2024-01-09 10:12 UTC, merged